### ISSUE TITLE
Unable to access all Salesforce objects : "Failed to retrieve query result"

### ISSUE THREAD

**Issue by benramsay** [pozil/salesforce-react-integration#17]
The first query is working fine (SELECT Id, Name FROM User LIMIT 10)

But not all objects seem accessible. This query does not work for example :
**Query** :  SELECT Id, Name FROM Product__c
**Error** : Failed to retrieve query result.
**Salesforce data API error**: {"name":"INVALID_TYPE","errorCode":"INVALID_TYPE"}

Actually I tried access objects of another project example by the same author, which is populating a table of products in the backend : https://github.com/trailheadapps/ebikes-lwc

It is a simple query inspired by a query in this page : 
https://github.com/trailheadapps/ebikes-lwc/blob/main/force-app/main/default/classes/ProductController.cls

Should I add some security configuration to salesforce backend ?
I put everything in selected OAuth scopes of the concerned connected app. But that doesn't help :(

![image](https://user-images.githubusercontent.com/96269862/204655746-25a5a759-d9fa-425d-96aa-2e576c541656.png)

If I do the same query from inside salesforce it works :
![image](https://user-images.githubusercontent.com/96269862/204759863-cb1d9456-396a-405f-8c55-a5348d3a00e5.png)

From the front-end
![image](https://user-images.githubusercontent.com/96269862/204760722-4ff23de5-0c25-490d-8874-dbc694e5f5d1.png)

Think you

**Comment by pozil** [comment]
Hi @benramsay, the only OAuth scope that you need for this sample project is the API scope.
Can you confirm that you're using the same user in the React app and the org? This could be a permission issue.
Also, I see that you've modified the appearance of the React app (the buttons at least), did you modify something else?

**Comment by benramsay** [comment]
Hi @pozil,
1/
First, I added a connected-app to the scratch org related to the alias ebikes.  
Then when clicked on login button in the React-application, and redirected to salesforce, I try to login with :
- the scratch-org username (related to the alias ebikes) and 
- the password generated with the command: sfdx force:user:password:generate
=> but salesforce did not allow me... However if I disconnect from the scratch org, I could reconnect using these credentials.

I don't understand what's missing with the configuration !


2/
I tryed then to connect to salesforce just with the my simple email (as user), (I mean the email used to create the salesforce account). I created a second connected app there and added new costume objects (then added data)
then changed the React-app .env file with the new tokens of the new connected app. 

In this second example, I have been able to login from the React-App (using my email, and SF password), and then retrive with SOQL query from the React Frontend,  the new data (related to those new costum objects) 
Every thing was working fine in this second case!

I emagine when logging to salesforce with my personal email as user, I will be on like a scratch org created by default. Isn"t it ?

So what is the difference between the two cases ? 
What is the difference beween that environement (related to my email) and the one related to the scratch org (ebikes) creacted with the cli commands ?

What is the difference between this environment (related to my personal email as user) and the one related to the scratch org (ebikes) created with the cli commands?

Thanks

**Comment by benramsay** [comment]
Great !  👍 

Actually, I copied the .env file as given in the Readme.md where :

> loginUrl='https://login.salesforce.com'

But in my case, using scratch orgs, it should be modified to

> loginUrl='https://test.salesforce.com'

I learned something about sf, and everything is now working as expected  👍 

You are my best salesforce friend :)

**Comment by pozil** [comment]
I'm glad that you were able to solve it. Happy to help.
